"""Generate one Markdown card per registered metric from the registry and the estimator docstrings.

Usage: python scripts/build_metric_cards.py  (writes docs/metrics/<name>.md and docs/metrics/README.md)
"""

from __future__ import annotations

import inspect
import re
from pathlib import Path

import req_metrics as rq

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "metrics"
BIB = (ROOT / "docs" / "references.bib").read_text(encoding="utf-8")


def bib_title(key: str) -> str:
    m = re.search(r"@\w+\{" + re.escape(key) + r",(.*?)\n\}", BIB, flags=re.S)
    if not m:
        return key
    body = m.group(1)
    t = re.search(r"title\s*=\s*[{\"](.*?)[}\"]\s*,?\s*\n", body, flags=re.S | re.I)
    y = re.search(r"year\s*=\s*[{\"]?(\d{4})", body)
    title = re.sub(r"[{}]", "", t.group(1)).strip() if t else key
    return f"{title} ({y.group(1)})" if y else title


def card(spec: rq.MetricSpec) -> str:
    fn = spec.fn
    doc = inspect.getdoc(fn.func if hasattr(fn, "func") else fn) or ""
    if doc.startswith(spec.description):  # the summary line is already the card header
        doc = doc[len(spec.description) :].lstrip("\n")
    file_name = spec.name.replace("/", "__")
    lines = [
        f"# `{spec.name}`",
        "",
        spec.description,
        "",
        f"- Input: `{spec.inputs.value}`",
        f"- Canonical preprocessing: `{spec.preprocess.describe()}`",
        f"- Tags: {', '.join(spec.tags) if spec.tags else 'none'}",
        f"- Shared cache: {spec.cache or 'none'}",
    ]
    if spec.arxiv:
        lines.append(f"- Origin: https://arxiv.org/abs/{spec.arxiv}")
    if spec.citation:
        lines.append("- Cite: " + "; ".join(f"`{k}` ({bib_title(k)})" for k in spec.citation))
    lines += ["", "## Definition, protocol and pitfalls", "", doc, ""]
    return "\n".join(lines), file_name


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    index = ["# Metric cards", "", "One card per registered metric, generated by `scripts/build_metric_cards.py`.", ""]
    for name in rq.list_metrics():
        text, file_name = card(rq.get_metric(name))
        (OUT / f"{file_name}.md").write_text(text, encoding="utf-8")
        index.append(f"- [`{name}`]({file_name}.md): {rq.get_metric(name).description}")
    (OUT / "README.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    print(f"wrote {len(rq.list_metrics())} cards to {OUT}")


if __name__ == "__main__":
    main()
